#define BUF_MP3_SIZE_FRAMES            16
#define BUF_MP3_SIZE_BYTES_PER_FRAME   1024
#define BUF_MP3_SIZE_BYTES              (BUF_MP3_SIZE_FRAMES * BUF_MP3_SIZE_BYTES_PER_FRAME)

#define MP3_SAMPLES_PER_FRAME       1152
#define BUF_PCM_SIZE_SAMPLES        20
#define BUF_PCM_SIZE_32BIT          (MP3_SAMPLES_PER_FRAME * BUF_PCM_SIZE_SAMPLES)

#define BUF_PCM_HALF_32BIT     (BUF_PCM_SIZE_32BIT / 2)
#define BUF_PCM_HALF_16BIT     (BUF_PCM_HALF_32BIT / 2)
#define BUF_PCM_SIZE_BYTES     (BUF_PCM_SIZE_32BIT * 4)    // wav around 1/8 seconds
#define BUF_PCM_HALF_BYTES     (BUF_PCM_SIZE_BYTES / 2)
